image: docker:git

services:
  - docker:dind

stages:
  - build_image
  - tag_latest

before_script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"

###
## BUILD IMAGE
#
# Default branches (master/dev)
build_image.default:
  stage: build_image
  script:
    - docker build --pull
      --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
      --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
      --build-arg VCS_REF="${CI_COMMIT_SHA:0:8}"
      -t "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME}" .
    - docker push "${CI_REGISTRY_IMAGE}:ansible-${CI_COMMIT_REF_NAME}"
  only:
    - master
  except:
    - tags
  tags:
    - docker
    
build_image.2320:
  stage: build_image
  script:
    - docker build --pull
      --build-arg VERSION='2.3.2.0'
      --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
      --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
      --build-arg VCS_REF="${CI_COMMIT_SHA:0:8}"
      -t "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME}" .
    - docker push "${CI_REGISTRY_IMAGE}:ansible-2.3.2.0"
  only:
    - master
  except:
    - tags
  tags:
    - docker
    
build_image.196:
  stage: build_image
  script:
    - docker build --pull
      --build-arg VERSION='1.9.6'
      --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
      --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
      --build-arg VCS_REF="${CI_COMMIT_SHA:0:8}"
      -t "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME}" .
    - docker push "${CI_REGISTRY_IMAGE}:ansible-1.9.6"
  only:
    - master
  except:
    - tags
  tags:
    - docker

# Issue branches (^[0-9]+-.*])
# Strip branch name branch ID
build_image.feature:
  stage: build_image
  script:
    - docker build --pull
      --build-arg VERSION=`tail -1 VERSION`
      --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
      --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
      --build-arg VCS_REF="${CI_COMMIT_SHA:0:8}"
      -t "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME%%-*}" .
    - docker push "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME%%-*}"
  only:
    - /^[0-9]+-.*$/
  except:
    - tags
  tags:
    - docker

# Non Standard branches (^[a-zA-Z]+.*)
# Strip branch name to 128 char max
build_image.nonstd:
  stage: build_image
  script:
    - docker build --pull
      --build-arg VERSION=`tail -1 VERSION`
      --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
      --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
      --build-arg VCS_REF="${CI_COMMIT_SHA:0:8}"
      -t "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME:0:128}" .
    - docker push "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME:0:128}"
  only:
    - /^[a-zA-Z]+.*$/
  except:
    - master
    - dev
    - tags
  tags:
    - docker

###
## TAG IMAGE
#
# Tag latest on master branch
tag_image.latest:
  stage: tag_latest
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME}"
    - docker tag "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME}" "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master
  except:
    - tags
  tags:
    - docker
