image: docker:git

services:
  - docker:dind

stages:
  - build_image
  - tag_image

before_script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"

###
## BUILD IMAGE
#
# Default branches (master/dev)
build_image.default:
  stage: build_image
  script:
    - docker build --pull
      --build-arg VERSION="${ANSIBLE_VERSION}"
      --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
      --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
      --build-arg VCS_REF="${CI_COMMIT_SHA:0:8}"
      -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" "${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}"
    - docker push "${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}" "${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}"
  only:
    - master
  except:
    - tags
  tags:
    - docker

# Issue branches (^[0-9]+-.*])
# Strip branch name branch ID
build_image.feature:
  stage: build_image
  script:
    - docker build --pull
      --build-arg VERSION="${ANSIBLE_VERSION}"
      --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
      --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
      --build-arg VCS_REF="${CI_COMMIT_SHA:0:8}"
      -t "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME%%-*}" .
    - docker push "${CI_REGISTRY_IMAGE}:branch-${CI_COMMIT_REF_NAME%%-*}"
  only:
    - /^[0-9]+-.*$/
  except:
    - tags
  tags:
    - docker

###
## TAG IMAGE
#
# Tag latest on master branch
tag_image.latest:
  stage: tag_image
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"

    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" "${CI_REGISTRY_IMAGE}:${ANSIBLE_VERSION}"
    - docker push "${CI_REGISTRY_IMAGE}:${ANSIBLE_VERSION}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" "${CI_REGISTRY_IMAGE}:latest"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" "${DOCKER_IMAGE}:${ANSIBLE_VERSION}"
    - docker push "${DOCKER_IMAGE}:${ANSIBLE_VERSION}" "${DOCKER_IMAGE}:${ANSIBLE_VERSION}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" "${DOCKER_IMAGE}:latest"
    - docker push "${DOCKER_IMAGE}:latest" "${DOCKER_IMAGE}:latest"

  only:
    - master
  except:
    - tags
  tags:
    - docker
